//Title
document.getElementById("title").innerText = "Biology 2B03 Exam Question Bank"

//Bank questions here
//bank.push(new question("", "", "", "", "", 1, ""));
//Module 5

//Module 6
bank.push(new question("In the Jak-STAT signalling pathway what is the function of STAT?", "It is a transcription factor.", "It causes dimerization of the receptor.", "It phosphorylates JAK.", "It is the ligand for the EpoR.", 1, "STAT is a transcription factor that mediates the cellular response to cytokines in the Jak-STAT pathway."));
bank.push(new question("Signaling between cells usually results in the activation of protein _______.", "nucleases", "lipases", "proteases", "kinases", 4, "Cell signaling often activates kinases, which are enzymes that transfer phosphate groups to proteins."));
bank.push(new question("Which of the following is NOT a typical event associated with cell signaling?", "Activation of G-proteins by exchanging GDP for GTP", "Stimulation of apoptosis", "Release of calcium ions from cell membranes", "Activation of protein kinases", 2, "Stimulation of apoptosis is not a typical signaling event; rather, it's a consequence of specific signaling pathways."));
bank.push(new question("Receptor tyrosine kinases are so called because...", "They autophosphorylate on threonine in response to ligand binding.", "They autophosphorylate on tyrosine in response to ligand binding.", "They contain SH2 domains that bind to phosphorylated tyrosines.", "They are phosphorylated by G-proteins in response to ligand binding.", 2, "Receptor tyrosine kinases are called so because they autophosphorylate on tyrosine residues in response to ligand binding."));
bank.push(new question("A cell secretes growth factors that have a slow diffusion rate, and interacting only with other cells in the immediate area is an example of _______________ signaling.", "exocrine", "synaptic", "paracrine", "cell contact", 3, "Paracrine signaling involves the release of signaling molecules that affect nearby cells in the immediate area."));
bank.push(new question("Sending a signal through the cell membrane can lead to the production of second messengers inside the cell. Which of the following can serve as second messengers?", "cAMP", "Ca++", "NO (nitric oxide)", "all of the above", 4, "All of the listed molecules (cAMP, Ca++, and NO) can serve as second messengers in cellular signaling pathways."));
bank.push(new question("Which of the following statements about G protein coupled receptors is true.", "GPCRs have intrinsic kinase activity and autophosphorylate in response to ligand binding.", "GPCRs are found only in animal cells, they have not been found in plant cells.", "GPCRs include the receptors in the eye that respond to light signals.", "GPCRs act through the second messenger GTP.", 3, "GPCRs include receptors in the eye that respond to light signals, such as rhodopsin."));
bank.push(new question("Some receptors for growth factors activate a protein kinase cascade, with the participation of multiple enzymes to effect a change in gene expression. Which of the following statements about a protein kinase cascade are true?", "External signals can lead to changes in gene expression.", "Multiple steps leading to kinase activations can result in cells having different responses, depending on the presence or absence of target proteins.", "Multiple steps in an activation mean that abnormal stimulation of a cell response such as growth can occur with mutations in more than one gene.", "All of the above are true.", 4, "All of the listed statements are true regarding protein kinase cascades and their role in gene expression and cellular responses."));
bank.push(new question("The endogenous GTPase activity of G-proteins serves to:", "synthesize cGMP as a second messenger.", "stimulate the activity of enzymes by producing energy.", "synthesize GTP as an energy source.", "hydrolyze GTP returning the G protein to a pre-stimulated level of activity.", 4, "The GTPase activity of G-proteins hydrolyzes GTP, returning the protein to its inactive state after signal transduction."));
bank.push(new question("In a fight-or-flight response, epinephrine released by the adrenal glands binds to a membrane receptor on muscle cells. Which of the following events result from ligand binding?", "G-protein is activated by binding GTP and causing adenylyl cyclase to produce cAMP.", "The second messenger, cAMP, activates protein kinase A which inhibits glycogen synthetase blocking glycogen synthesis.", "Protein kinase A activates phosphorylase kinase, which transfers a phosphate that activates glycogen phosphorylase. This leads to the breakdown of glycogen and the production of glucose-6-phosphate.", "All of the above.", 4, "All of the listed events are part of the signaling pathway initiated by epinephrine during the fight-or-flight response, leading to glycogen breakdown and glucose production."));

//Module 7
bank.push(new question("Which statement is true for the assembly of actin filaments?", "The basic subunit of an actin filament is F-actin.", "Actin subunits must be in the ADP-bound form to be added to the growing filament.", "Treadmilling occurs when the rate of addition at the plus end equals the rate of disassembly at the minus end.", "GEFs exchange ADP for ATP in the actin subunit.", 3, "Treadmilling refers to the dynamic process where actin filaments grow at the plus end while disassembling at the minus end, maintaining a constant filament length."));
bank.push(new question("What is a motor protein associated with microtubules?", "myosin", "kinesin", "dynamin", "tubulin", 2, "Kinesin is a motor protein that moves along microtubules, typically involved in transporting cellular cargo."));
bank.push(new question("Which of the following statements is true regarding the role of microtubules?", "The mitotic spindle forms with the MT plus ends attaching to the MTOC.", "The mitotic spindle forms with the MT minus ends attaching to the periphery of the cell.", "The mitotic spindle forms with the MT plus ends attaching to the kinetochores.", "The mitotic spindle forms with the MT minus ends attaching to the kinetochores.", 3, "During mitosis, the plus ends of microtubules attach to the kinetochores, helping to align and separate chromosomes."));
bank.push(new question("Which of the following statements about microtubules is true?", "Microtubules are assembled at the minus end, unlike actin filaments.", "Heterodimers of alpha and beta tubulin must be in the GTP bound form to be added to the growing microtubule.", "Microtubules are the thinnest of the cytoskeletal fibers.", "Microtubules consist of homodimers of alpha-tubulin.", 2, "Heterodimers of alpha and beta tubulin in the GTP-bound form are required for the addition of subunits to the growing microtubule."));
bank.push(new question("Which of the following is not part of the cytoskeleton?", "actin filament", "intermediate filament", "microtubule", "myosin filament", 4, "Myosin filaments are motor proteins, not part of the cytoskeleton, which includes actin filaments, intermediate filaments, and microtubules."));
bank.push(new question("Which of the following statements is true about movement along microtubules?", "Kinesin is a motor protein that moves towards the minus end of a microtubule.", "Energy is required in the form of GTP hydrolysis.", "The tail of a motor protein is the part that 'walks' along the MT.", "Dynein is a motor protein that moves towards the minus end of a microtubule.", 4, "Dynein is a motor protein that moves toward the minus end of microtubules, while kinesin moves toward the plus end."));
bank.push(new question("Which of the following cellular processes involve microtubules?", "formation of the contractile ring at cytokinesis", "contraction of sarcomeres", "cellular movement through filopodia.", "formation of the mitotic spindle", 4, "Microtubules are essential for the formation of the mitotic spindle during cell division."));
bank.push(new question("Which of the following cellular processes is not a function involving actin filaments?", "formation of the mitotic spindle", "movement through lamellipodia", "contraction of the cytoplasm", "formation of the contractile ring in cytokinesis", 1, "The formation of the mitotic spindle involves microtubules, not actin filaments."));

//Module 8
bank.push(new question("Which of the following is not part of an adherens junction?", "Cadherin", "beta-catenin", "tubulin", "actin", 3, "Tubulin is not part of an adherens junction; this junction involves cadherins, beta-catenin, and actin filaments."));
bank.push(new question("When cells form junctions it has been shown experimentally that E-cadherin interacts with another E-cadherin. This is an example of a:", "Hydrophobic interaction.", "Hydrophilic interaction.", "Homophilic interaction.", "Heterophilic interaction.", 3, "Homophilic interaction occurs when similar molecules, like E-cadherin, interact with each other on adjacent cells."));
bank.push(new question("In rolling adhesion what do the selectins interact with on the surface of the leukocyte?", "protein receptors in the membrane.", "carbohydrate groups on the membrane.", "Phospholids in the membrane.", "non-specific proteins in the membrane.", 2, "Selectins interact with carbohydrate groups on the surface of the leukocyte during rolling adhesion."));
bank.push(new question("Tight binding of leukocytes is mediated through:", "Integrins", "Receptors", "Selectins", "Cytokines", 1, "Integrins mediate the tight binding of leukocytes to endothelial cells during inflammation."));
bank.push(new question("Which of the following statements is true for the plasmodesmata of plant cells?", "They form the junctions between cells of the xylem.", "They allow for gaseous exchange in leaves.", "They are similar in function to tight junctions in animal cells.", "They form the sieve tube plate between phloem cells.", 4, "Plasmodesmata form the sieve tube plates between phloem cells, allowing for the transport of nutrients and signaling molecules."));
bank.push(new question("Which of the following proteins is NOT an extracellular CAM?", "Cadherin", "Integrin", "Catenin", "Selectin", 3, "Catenin is not an extracellular CAM; it is an intracellular protein that interacts with cadherins."));
bank.push(new question("What is the order of events in extravasation?", "1. capture, 2. slow rolling, 3. transmigration, 4. firm adhesion", "1. slow rolling, 2. capture, 3. firm adhesion, 4. transmigration", "1. capture, 2. rolling, 3. slow rolling, 4. firm adhesion", "1. capture, 2. firm adhesion, 3. slow rolling, 4. extravasation", 3, "The correct order is: 1. capture, 2. rolling, 3. slow rolling, 4. firm adhesion during the process of extravasation."));
bank.push(new question("Which of the following is true regarding the importance of the development of cell adhesion?", "It allows for cells of similar function to segregate into specific organs", "It is needed for the transmigration of leukocytes through an endothelial cell layer", "It triggers apoptosis during embryo development", "It is responsible for metastasis of cancer cells", 1, "Cell adhesion allows cells of similar function to group together and form tissues and organs during development."));

//Module 9
bank.push(new question("Mitosis is the process by which a cell divides to produce two daughter cells. During which phase of mitosis do the chromosomes attach to the mitotic spindle?", "prophase", "prometaphase", "metaphase", "anaphase", 2, "During prometaphase, the chromosomes attach to the mitotic spindle via their kinetochores."));
bank.push(new question("Mitosis is the process by which a cell divides to produce two daughter cells. During which phase of mitosis do the sister chromatids separate?", "prophase", "prometaphase", "metaphase", "anaphase", 4, "During anaphase, the sister chromatids are pulled apart toward opposite poles of the cell."));
bank.push(new question("The cell cycle is controlled by phosphorylation of many proteins involved in the process. This phosphorylation is carried out by a family of proteins called Cyclin-CDK complexes which act at different stages of mitosis. G1 cyclin-CDK complexes function in G1, which of the following is NOT an activity of the G1 cyclin CDK?", "induces degradation of S-phase inhibitors", "prepare cells for S phase", "induce synthesis of proteins required for DNA synthesis", "assembles the pre-replication complex to initiate DNA synthesis", 4, "Assembling the pre-replication complex to initiate DNA synthesis is the function of the S-phase cyclin-CDK, not G1 cyclin-CDK."));
bank.push(new question("Which of the following statements is NOT true for the M cyclin-CDK complexes?", "phosphorylate transcription factors required for synthesis of S-phase proteins", "phosphorylate proteins involved in nuclear envelope breakdown", "includes the Maturation Promoting Factor", "phosphorylate proteins that activate Anaphase Promoting Factor", 1, "M cyclin-CDK complexes do not phosphorylate transcription factors required for the synthesis of S-phase proteins, which is typically the role of G1 cyclin-CDKs."));
bank.push(new question("When studying a process such as cell division, why is it necessary to use TS mutants?", "Gene knockouts are difficult to generate.", "Because different organisms grow at different temperatures.", "Gene knockouts are not viable and so cannot be isolated.", "Gene knockouts are viable but cannot be used for complementation studies.", 3, "Gene knockouts are often not viable, making them difficult to study directly, so TS mutants are used to conditionally disable genes at specific temperatures."));
bank.push(new question("The genes involved in cell cycle regulation were studied in model systems such as yeast using temperature sensitive mutants. What is a temperature sensitive mutant?", "A mutation in a gene that allows the protein to function normally at a 'restrictive' temperature but not at the 'permissive' temperature.", "A mutation in a gene that allows the protein to function normally at a 'permissive' temperature but not at the 'restrictive' temperature.", "A mutation in a gene that causes it to fold normally but have no function at both 'permissive' and 'restrictive' temperatures.", "A mutation in a gene such that it is only expressed at the 'permissive' temperature but not at the 'restrictive' temperature.", 2, "A temperature-sensitive mutant allows the protein to function normally at the permissive temperature but not at the restrictive temperature, enabling conditional gene inactivation."));
bank.push(new question("In S. pombe cells, the small cell phenotype is the result of:", "The small cells are a result of an increased Cdc25 activity.", "The small cells are a result of an increase in Wee1 activity.", "The small cells are a result of a decrease in Cdc25 activity.", "The small cells are a result of an extended G2.", 1, "The small cell phenotype in S. pombe is caused by increased Cdc25 activity, leading to premature entry into mitosis."));
bank.push(new question("Activation of MPF requires several steps. What is the role of Cdc25 in MPF activation?", "Cdc25 is a phosphatase that removes phosphate from Threonine 161.", "Cdc25 is a kinase that phosphorylates Tyrosine 15.", "Cdc25 is a phosphatase that removes phosphate from Tyrosine 15.", "Cdc25 is a kinase that phosphorylates Threonine 161.", 3, "Cdc25 is a phosphatase that removes the phosphate from Tyrosine 15, activating MPF and allowing the cell to progress through the cell cycle."));
bank.push(new question("The basic mechanisms of cell cycle control are similar in mammalian cells, using cyclin-CDK complexes to regulate progression through the cycle. There are, however, differences due to the fact that we are multicellular organisms. Which of the following statements is true for the mammalian cell cycle?", "Most cells within the organism are in G1.", "Re-entry into the cell cycle usually requires activation by mitogens.", "Most cells, once differentiated, can easily re-enter the cell cycle.", "Cyclins and CDKs are expressed in G0 but are not activated.", 2, "In mammalian cells, re-entry into the cell cycle typically requires activation by mitogens, which trigger the progression from G0 or G1 to S phase."));

//Module 10
bank.push(new question("As a cell enters mitosis the now active MPF mediates phosphorylation of many of the key proteins required for progression through prophase. What are the targets of MPF phosphorylation involved in endomembrane fragmentation?", "cohesins", "GM130", "microtubule associated proteins", "lamins", 2, "GM130 is a target of MPF phosphorylation involved in the fragmentation of endomembranes during mitosis."));
bank.push(new question("As a cell enters mitosis the now active MPF mediates phosphorylation of many of the key proteins required for progression through prophase. What are the targets of MPF phosphorylation involved in nuclear envelope breakdown?", "condensins and histones", "cohesins", "GM130", "lamins", 4, "Lamins are the targets of MPF phosphorylation involved in the breakdown of the nuclear envelope during mitosis."));
bank.push(new question("Which of the following is not an event of telophase?", "nuclear envelope reforms", "chromosome decondensation", "ER reassembles", "activation of MPF", 4, "Activation of MPF occurs earlier in the cell cycle and is not part of the events that occur during telophase."));
bank.push(new question("Which of the following statements is true about nucleosomes and histones?", "H1 and H3 are phosphorylated for mitosis to proceed.", "H2a and b and H4 are phosphorylated for mitosis to proceed.", "DNA is unwound from the histones during condensation.", "H1 and H3 form a dimer when phosphorylated.", 1, "H1 and H3 are phosphorylated to facilitate the progression of mitosis."));
bank.push(new question("Which of the following statements is not true regarding the breakdown of the nuclear envelope?", "Before condensation, chromatin is associated with lamins at the nuclear membrane.", "Lamins exist as tetramers that dissociate into dimers on phosphorylation.", "phosphorylation results in lamin A and B being dispersed into the cytosol", "Lamin B remains associated with the membrane during NEB.", 3, "Phosphorylation causes lamin A and B to be dispersed into the cytosol, not remaining at the nuclear membrane during nuclear envelope breakdown (NEB)."));
bank.push(new question("Which of the following statements about mitogens is not true?", "They are growth factors that induce G1 in a resting cell.", "They are required until the cell passes the Restriction Point.", "They regulate phosphorylation of transcription factors by MAP kinase.", "They induce phosphorylation of the transcription factor c-fos.", 4, "Mitogens do not directly induce phosphorylation of the transcription factor c-fos; they typically regulate the activation of MAP kinase and other signaling pathways."));
bank.push(new question("c-fos is an example of an early gene. Which of the following statements is true about c-fos?", "It is activated by the delayed response genes.", "It is a transcription factor that activates the early response genes.", "In response to a mitogen it does not need to be translated, just phosphorylated.", "It is a transcription factor that transcribes the delayed response genes.", 4, "c-fos is a transcription factor that activates delayed response genes after being transcribed and translated in response to mitogen signaling."));
bank.push(new question("Which statement is not true about the Restriction Point?", "If mitogen is removed before the Restriction Point is reached cells will divide.", "It occurs in G1 before S-phase.", "If mitogen is removed after the Restriction Point cells will divide.", "It signifies commitment by the cell to proceed through the cell cycle.", 1, "If mitogen is removed before the Restriction Point, the cell will not divide, as it has not yet committed to proceeding through the cell cycle."));
bank.push(new question("Which of the following is not a cell cycle checkpoint?", "G2 arrest to check for proper spindle formation.", "S-phase arrest to check for unreplicated DNA.", "G2 arrest to check for DNA damage.", "G1 arrest to check for DNA damage.", 1, "G2 arrest checks for DNA damage, not spindle formation, which is specifically checked during mitosis."));
