//Bank questions here
//bankBiochem3h03t2.push(new question("", "", "", "", "", 1, ""));

//Lecture 1 Intro
bankBiochem3h03t2.push(new question("What is the difference between serum and plasma?", "Serum lacks clotting factors that plasma has", "Serum is the aqueous phase of blood, while plasma is coagulated blood", "Serum has white blood cells and platelets which can provide more information about the blood", "There is no difference between serum and plasma", 1, "Serum and plasma are both from the aqueous phase of blood, but unlike serum, plasma still has coagulation factors despite not clotting. Plasma is preserved by anticoagulants."));
bankBiochem3h03t2.push(new question("What is the difference between the Reference Interval (RI) and the Clinical Decision Limit (CDL)?", "The RI is arbitrary while the CDL is based on population statistics", "The RI is used for clinical decision making while the CDL is used for identifying deviations from the average in the general population", "The RI is based on the general population and the CDL is based on the clinical population", "The RI is based on clinical studies and guidelines while the CDL is the 95% central interval of the reference distribution", 3, "The RI is based on the general population, and is based on the 95% central interval of the reference distribution. The CDL is based on studies and guidelines for the clinical population and is used for clinical decision making. The CDL can change because of how they are based."));
bankBiochem3h03t2.push(new question("What is the difference between sensitivity in tests and specificity?", "Sensitivity is the ability to identify patients without the disease and specificity is the ability to identify patients with the disease", "High sensitivity is good for identifying a diagnosis, while high specificity is good for ruling out a diagnosis", "Sensitivity is the percentage of unaffected individuals who have a negative test result, specificity is the percentage of affected individuals who have a positive test result", "Sensitivity is measured by how often a test picks up a disease, while specificity is measured by how good a test is at ignoring those without the disease", 4, "Sensitivity is calculated based on how well a test picks up a disease, and specificity is calculated based on how specific it is only to individuals who are truly affected."));
bankBiochem3h03t2.push(new question("In a population that is given a test for disease, 6 return a true negative, 1 returns a false negative, 1 returns a true positive, and 2 return a false positive. What is the sensitivity and specificity of the test?", "Sensitivity: 0.5, Specificity: 0.75", "Sensitivity: 50, Specificity: 75", "Sensitivity: 33.3, Specificity: 85.7", "Sensitivity: 0.333, Specificity: 0.857", 2, "Sensitivity is calculated by the amount of individuals with a true positive divided by the amount of affected individuals, times 100 (TP/(TP+FN) * 100), and specificity is calculated by the amount of individuals with a true negative divided by the amount of unaffected individuals, times 100 (TN/(TN+FP) * 100)."));

//Lecture 2A Fluids
bankBiochem3h03t2.push(new question("How much body water is stored in the intracellular compartment?", "1/3", "3/4", "1/4", "2/3", 4, "The intracellular compartment (ICF) contains around 2/3 of body water. The remaining 1/3 is in the ECF, with plasma holding 1/4 of it and interstitial fluid holding the other 3/4."));
bankBiochem3h03t2.push(new question("Which is the major extracellular cation?", "Potassium", "Sodium", "Lithium", "Hydronium", 2, "Sodium is the major extracellular cation. Potassium is the major intracellular cation."));
bankBiochem3h03t2.push(new question("What does it mean when the intracellular and extracellular fluids are isotonic?", "They have different osmolalities", "They have equal amounts of water", "They have the same osmolalities", "They have equal amounts of sodium", 3, "Isotonic means that the ICF and ECF have the same osmotic concentrations, or osmolalities, primarily determined by sodium concentration."));
bankBiochem3h03t2.push(new question("What is the pathway of aldosterone production in the Renin Angiotensin Aldosterone System (RAAS)?", "Prorenin --> Renin --> Angiotensin I --> Angiotensin II --> Aldosterone", "Angiotensin I --> Angiotensin II --> Prorenin --> Renin --> Aldosterone", "Prorenin --> Renin --> Angiotensin II --> Angiotensin I --> Aldosterone", "Angiotensin II --> Angiotensin I --> Prorenin --> Renin --> Aldosterone", 1, "The pathway of aldosterone production is: Prorenin --> (Cleaved) --> Renin --> (Released in blood, cleaves Angiotensinogen) --> Angiotensin I --> (Converted) --> Angiotensin II --> (Stimulates release from adrenal cortex) --> Aldosterone."));
bankBiochem3h03t2.push(new question("What is another name for ADH?", "Aldosterone", "Vasopressin", "Renin", "Angiotensin I", 2, "Another name for antidiuretic hormone (ADH) is vasopressin."));
bankBiochem3h03t2.push(new question("What is the purpose of Aldosterone?", "To promote water retention", "To promote potassium retention", "To promote sodium loss", "To increase ECF volume", 4, "Aldosterone helps increase ECF volume by promoting sodium retention in the kidneys, which draws water into the ECF."));
bankBiochem3h03t2.push(new question("What is the purpose of Vasopressin (ADH)?", "To promote sodium retention", "To increase ECF osmolality", "To promote water retention", "To decrease ECF volume", 3, "ADH promotes water reabsorption in the kindneys when the ECF osmolality is elevated and ECF volume is lowered."));
bankBiochem3h03t2.push(new question("When might ADH and Aldosterone be released together?", "Low blood pressure", "High salt intake", "High water intake", "Dilute urine", 1, "Low blood pressure can cause both ADH and Aldosterone to be released together. It decreases ECF volume, which releases ADH, and the decreased ECF volume also triggers the RAAS pathway, which releases Aldosterone."));
bankBiochem3h03t2.push(new question("When might ADH be released but not Aldosterone?", "Low blood pressure", "High salt intake", "High water intake", "Dilute urine", 2, "High salt intake without enough water can release ADH due to increased ECF osmolality, but not Aldosterone because the abundance of salt in the ECF draws water into the ECF and increases volume, which suppresses the RAAS pathway."));

//Lecture 2B Fluids
bankBiochem3h03t2.push(new question("What is the threshold plasma sodium concentration for Hyponatremia?", "<146 mmol/L", "<133 mmol/L", ">146 mmol/L", ">133 mmol/L", 2, "The threshold plasma concentration for Hyponatremia is 133 mmol/L. Below that, a patient may have Hyponatremia."));
bankBiochem3h03t2.push(new question("Which of the following is not a cause of true Hyponatremia?", "Hyperlipidemia", "Hyperglycemia if osmolality is low", "Dilutional Hyponatremia", "All of the above are causes of true Hyponatremia", 1, "Hyperlipidemia causes Pseudohyponatremia by lowering the water fraction in serum, resulting in indirect (diluted) measurements showing lower sodium concentration. Hyperglycemia can cause Pseudohyponatremia if the osmolality is within range, but if it is low, it can cause true Hyponatremia (High Glucose --> ICF water to ECF --> Low Na+). Dilutional Hyponatremia decreases sodium concentration by adding water into the ECF (Excess ECF water --> Low Na+, respectively)."));
bankBiochem3h03t2.push(new question("How can someone with Pseudohyponatremia have their sodium levels evaluated correctly?", "Have them drink 2L of water right before measurement", "Add saline solution to the sample to increase the water fraction", "Measure the undiluted sample directly", "It's impossible, you can only estimate it", 3, "Pseudohyponatremia can be avoided by using a direct measurement of the sample."));
bankBiochem3h03t2.push(new question("A patient has 125 mmol/L Na+, elevated cholesterol, and normal serum osmolality with a history of Hyperlipidemia. What is a likely diagnosis?", "Pseudohyponatremia", "Hyponatremia", "Hypernatremia", "No issue", 1, "High cholesterol and a history of Hyperlipidemia indicates the possibility of Pseudohyponatremia caused by elevated serum lipids."));
bankBiochem3h03t2.push(new question("A patient has 127 mmol/L Na+, normal cholesterol, and low serum osmolality. What is a likely diagnosis?", "Pseudohyponatremia", "Hyponatremia", "Hypernatremia", "No issue", 2, "A low Na+ concentration (<133 mmol/L) with low serum osmolality and no other abnormal readings indicates true Hyponatremia, possibly dilutional from high water intake."));
bankBiochem3h03t2.push(new question("What is the threshold plasma sodium concentration for Hypernatremia?", ">133 mmol/L", "<133 mmol/L", "<146 mmol/L", ">146 mmol/L", 4, "The threshold plasma concentration for Hypernatremia is 146 mmol/L. Above that, a patient may have Hypernatremia."));
bankBiochem3h03t2.push(new question("A patient has 167 mmol/L Na+, normal cholesterol, and high serum osmolality with low blood pressure. What is a likely diagnosis?", "Pseudohyponatremia", "Hyponatremia", "Hypernatremia", "No issue", 3, "High Na+ concentration (>146 mmol/L) with high serum osmolality and low blood pressure indicates Hypernatremia, possibly from low water intake."));
bankBiochem3h03t2.push(new question("A patient has 135 mmol/L Na+, normal cholesterol, and normal serum osmolality. What is a likely diagnosis?", "Pseudohyponatremia", "Hyponatremia", "Hypernatremia", "No issue", 4, "Na+ concentration within the normal range (133 mmol/L - 146 mmol/L) does not indicate any sodium imbalance."));

//Lecture 3A Hydrogen Ion
bankBiochem3h03t2.push(new question("Where is excess CO2 removed from the body?", "Lungs", "Kidneys", "Liver", "Heart", 1, "Excess CO2 is removed from the body through exhalation in the lungs."));
bankBiochem3h03t2.push(new question("Where is excess H+ removed from the body?", "Liver", "Lungs", "Heart", "Kidneys", 4, "Excess H+ ions are excreted through the kidneys."));
bankBiochem3h03t2.push(new question("What is the pathway that CO2 takes to increase H+ levels in the ECF?", "CO2 + H2O <--> CO3(2-) + 2H+", "CO2 + H2O <--> HCO3- + H+", "CO2 + H2O <--> H2CO3 <--> HCO3- + H+", "CO2 + CH4 <--> CH3COO- + H+", 3, "CO2 first gets converted to H2CO3 when combined with water, which can then dissociate into HCO3- and H+ ions. This increases H+ levels in the ECF."));
bankBiochem3h03t2.push(new question("What is the ECF's main buffer system?", "H2PO4- / HPO4(2-)", "H3O+ / OH-", "HCl / Cl-", "H2CO3 / HCO3-", 4, "The ECF's main buffer system is the Carbonic Acid - Bicarbonate system. It uses this system to regulate excess charged ions."));
bankBiochem3h03t2.push(new question("What form does CO2 mostly take in the bloodstream?", "CO2", "H2CO3", "HCO3-", "None of the above", 3, "Carbon dioxide mostly takes the form of bicarbonate, as part of the H2CO3 / HCO3- buffer. Bicarbonate is more common because the pH of blood needs to be 7.35-7.45."));
bankBiochem3h03t2.push(new question("Where is carbon dioxide converted into bicarbonate?", "Lungs", "Liver", "Red Blood Cells", "Heart", 3, "Carbon dioxide is converted into bicarbonate in the red blood cells."));
bankBiochem3h03t2.push(new question("How can blood CO2 concentration be measured?", "By cooling it to liquid CO2", "By measuring HCO3- concentration", "By measuring H+ concentration", "By measuring the partial pressure of CO2", 4, "Blood CO2 can be measured by its partial pressure."));
bankBiochem3h03t2.push(new question("Which of the following statements is true?", "[H2CO3] is inversely proportional to P(CO2)", "[H+] is proportional to [HCO3-]", "[H2CO3] is proportional to [HCO3-]", "[H+] is proportional to P(CO2)", 4, "H+ concentration is directly proportional to P(CO2)."));
bankBiochem3h03t2.push(new question("How do we assess acid-base homeostasis in the blood?", "Urine sample", "Arterial blood gas test", "Blood cell test", "Kidney acidity test", 2, "Arterial blood gas (ABG) tests are used to assess acid-base homeostasis in the blood since it can collect information about CO2 and O2 partial pressures. It is usually taken from the radial / brachial artery."));

//Lecture 3B Hydrogen Ion
bankBiochem3h03t2.push(new question("What can cause metabolic acidosis?", "Increased H+ formation (diabetic ketoacidosis, ethanol poisoning)", "Decreased H+ excretion (kidney failure)", "Loss of HCO3- (diarrhea)", "All of the above", 4, "All of the above contribute to elevated [H+], causing metabolic acidosis."));
bankBiochem3h03t2.push(new question("How can you identify metabolic acidosis?", "Increased [H+], Decreased P(CO2), Increased [HCO3-]", "Decreased [H+], Decreased P(CO2), Decreased [HCO3-]", "Increased [H+], Slightly Decreased P(CO2), Decreased [HCO3-]", "Increased [H+], Increased P(CO2), Increased [HCO3-]", 3, "Metabolic acidosis is featured by an increase of [H+] and a reduction in [HCO3-]. CO2 is also reduced through hyperventilation, a compensatory mechanism for acidosis."));
bankBiochem3h03t2.push(new question("A patient has blood pH 7.05, elevated [H+], normal P(CO2), and low [HCO3-]. What is the diagnosis?", "Metabolic Acidosis", "Respiratory Acidosis", "Metabolic Alkalosis", "Respiratory Alkalosis", 1, "Acidosis can be identified by the elevated [H+] (Do not assess the pH first, you will lose marks). It can be identified to be metabolic since [HCO3-] is lowered and P(CO2) is in range."));
bankBiochem3h03t2.push(new question("How should acid-base disorders be interpreted in a blood gas test?", "[H+] (Acidosis or alkalosis) --> [HCO3-] and P(CO2) (Metabolic or respiratory)", "pH (Acidosis or alkalosis) --> [HCO3-] and P(CO2) (Metabolic or respiratory) --> [H+] (Verify acidosis or alkalosis)", "[HCO3-] and P(CO2) (Metabolic or respiratory) --> [H+] (Acidosis or alkalosis)", "[HCO3-] and P(CO2) (Metabolic or respiratory) --> pH (Acidosis or alkalosis)", 1, "[H+] is assessed first to determine acidosis (high) or alkalosis (low), then [HCO3-] and P(CO2) will be assessed to determine metabolic (low [HCO3-], slightly low P(CO2)) or respiratory (normal [HCO3-], high P(CO2))."));
bankBiochem3h03t2.push(new question("A patient has blood pH 7.24, elevated [H+], elevated P(CO2), and normal [HCO3-]. What is the diagnosis?", "Metabolic Acidosis", "Respiratory Acidosis", "Metabolic Alkalosis", "Respiratory Alkalosis", 2, "Acidosis can be identified by the elevated [H+] (Do not assess the pH first, you will lose marks). It can be identified to be respiratory since [HCO3-] is in range and P(CO2) is elevated."));
bankBiochem3h03t2.push(new question("How is respiratory acidosis corrected?", "Increase bicarbonate production by lowering blood pH", "Drinking water to promote excretion of H+ ions", "Inducing diarrhea to lower [HCO3-]", "Improving ventilation", 4, "Respiratory acidosis, caused by elevated blood CO2, can be corrected by improving ventilation and the exhalation of CO2."));
bankBiochem3h03t2.push(new question("What can cause respiratory acidosis?", "Airway obstruction", "Neuromuscular diseases", "Pulmonary disease", "All of the above", 4, "All of the above can affect breathing, leading to decreased excretion of CO2, which can cause respiratory acidosis."));
bankBiochem3h03t2.push(new question("A patient has blood pH 7.56, low [H+], slightly elevated P(CO2), and elevated [HCO3-]. What is the diagnosis?", "Metabolic Acidosis", "Respiratory Acidosis", "Metabolic Alkalosis", "Respiratory Alkalosis", 3, "Alkalosis can be identified by the lower [H+] (Do not assess the pH first, you will lose marks). It can be identified to be metabolic since [HCO3-] is elevated and P(CO2) is only slightly elevated."));
bankBiochem3h03t2.push(new question("Why is the compensatory mechanism for metabolic alkalosis not hypoventilation?", "Increased P(CO2) will further contribute to alkalosis", "Hypoventilation does not increase P(CO2)", "The lack of oxygen from not breathing is a more powerful stimulus than the increased P(CO2) from hypoventilation", "Hypoventilation in combination with metabolic alkalosis risks getting alkalosis and acidosis at the same time", 3, "Hypoventilation, and the lack of breathing, reduces oxygen levels, which the body dislikes, which means hypoventilation would not be an appropriate compensatory mechanism."));
bankBiochem3h03t2.push(new question("How can you identify metabolic alkalosis?", "Decreased [H+], Increased P(CO2), Decreased [HCO3-]", "Decreased [H+], Decreased P(CO2), Decreased [HCO3-]", "Decreased [H+], Slightly Increased P(CO2), Increased [HCO3-]", "Increased [H+], Increased P(CO2), Increased [HCO3-]", 3, "Metabolic acidosis is featured by a decrease of [H+] and an increase in [HCO3-]. P(CO2) can also be slightly elevated."));
bankBiochem3h03t2.push(new question("A patient has blood pH 7.52, lower [H+], lower P(CO2), and slightly decreased [HCO3-]. What is the diagnosis?", "Metabolic Acidosis", "Respiratory Acidosis", "Metabolic Alkalosis", "Respiratory Alkalosis", 4, "Alkalosis can be identified by the lower [H+] (Do not assess the pH first, you will lose marks). It can be identified to be metabolic since [HCO3-] is slightly lower and P(CO2) is lower."));
bankBiochem3h03t2.push(new question("Which of the following is false?", "Respiratory compensation is fast (minutes to hours)", "Respiratory compensation can happen completely", "Metabolic compensation is slow (hours to days)", "Metabolic compensation can happen completely", 2, "Respiratory compensation is quick but cannot happen completely. Metabolic compensation is slow but can happen almost completely, given enough time."));

//Lecture 4A Kidneys
bankBiochem3h03t2.push(new question("What is the functional unit of the kidneys?", "Renal Artery", "Nephron", "Renal Pelvis", "Ureter", 2, "The nephron is the functional unit of the kidneys."));
bankBiochem3h03t2.push(new question("Where in the nephron is blood filtered?", "Glomeruli", "Proximal Tubules", "Loops of Henle", "Distal Tubules", 1, "Blood is filtered through the Glomeruli. The ultrafiltrate is similar to plasma, except without large proteins."));
bankBiochem3h03t2.push(new question("Where in the nephron does ultrafiltrate get reabsorbed?", "Glomeruli", "Proximal Tubules", "Loops of Henle", "Distal Tubules", 2, "Glomerular ultrafiltrate gets reabsorbed in the proximal tubules."));
bankBiochem3h03t2.push(new question("Where does additional water get reabsorbed through the countercurrent system?", "Glomeruli", "Proximal Tubules", "Loops of Henle", "Distal Tubules", 3, "The ultrafiltrate goes through a countercurrent (against the current of the ultrafiltrate) reabsorption system, where Na+ and Cl- are pumped out, increasing osmolality and drawing water back into the body."));
bankBiochem3h03t2.push(new question("Where is sodium reabsorption fine-tuned and excess H+ excreted with ammonia?", "Glomeruli", "Proximal Tubules", "Loops of Henle", "Distal Tubules", 4, "Fine-tuning as well as excess H+ ion excretion occur in the distal tubules."));
bankBiochem3h03t2.push(new question("Why is creatinine used to assess glomerular filtration rate (GFR)?", "Creatinine binds tightly to water", "Creatinine binds tightly to Na+", "Creatinine does not get reabsorbed in the kidneys", "Creatinine suppresses the reabsorption mechanism in the nephrons", 3, "Creatinine does not get reabsorbed in the kidneys, so it can be used to calculate the efficiency of filtration in the Glomeruli."));
bankBiochem3h03t2.push(new question("What limitations do creatinine GFR tests have?", "Plasma creatinine is not very sensitive to Glomeruli function, and can read within range even with GFR issues", "Many processes can alter plasma creatinine levels, limiting its accuracy in diagnosing GFR issues", "Both of the above", "None of the above; it is a reliable test in all cases", 3, "Both insensitivity of plasma creatinine to GFR issues and disruptions in plasma creatinine are limitations that may necessitate further GFR testing in some cases."));
bankBiochem3h03t2.push(new question("What might we see in patients with impaired glomerular integrity?", "Hyponatremia", "Hypernatremia", "Higher than normal urine creatinine", "Albuminuria", 4, "Albuminuria can be detected in patients with impaired glomerular integrity. It is in the form of albuminuria when measured with a urine dipstick and microalbuminuria when detected in laboratory analysis."));
bankBiochem3h03t2.push(new question("What might we see in patients with severe glomerular damage?", "Hyponatremia", "Albuminuria", "Hematuria", "None of the above", 3, "Hematuria (red blood cells in urine) can be detected in patients with severe glomerular damage, and can be in the form of microhematuria or macrohematuria."));
bankBiochem3h03t2.push(new question("A patient has been diagnosed with diabetes mellitus (DM), and the doctor orders a urine albumin test. Why?", "Glucose catalyzes albumin production in the kidneys", "Glucose catalyzes albumin production outside the kidneys", "DM patients have a higher risk of kidney disease, and early detection helps prevent disease progression", "Glucose damages the glomerulus, and testing urine albumin levels can determine the need for a kidney replacement", 3, "DM patients have an increased risk of kidney disease. 7-10 years after DM onset, the damage done to the kidneys can increase permeability and lead to albuminuria. Early detection can help prevent the progression of kidney disease."));

//Lecture 4B Kidneys
bankBiochem3h03t2.push(new question("A patient took a urine test and has moderate leukocytes, moderate RBCs, nitrite positive, and everything else in range. What is the most likely explanation?", "UTI", "Impaired glomerular integrity", "Diabetes", "Albuminuria", 1, "Leukocytes and nitrite in the urine are markers of a UTI. RBCs suggest bleeding in the urinary tract."));
bankBiochem3h03t2.push(new question("A patient took a urine test and has a small presence of bacteria and yeast. What is the most likely explanation?", "Hematuria", "UTI", "Albuminuria", "Severe glomerular damage", 2, "Bacteria or yeast could indicate a UTI, but could also indicate contamination of the sample."));
bankBiochem3h03t2.push(new question("What assesses renal tubular function in urinalysis?", "Proteins and Glucose", "Nitrites and Leukocytes", "Bilirubin", "Bacteria and Yeast", 1, "Protein and glucose levels in the urine can help assess renal tubular function."));
bankBiochem3h03t2.push(new question("What is a marker of a UTI in urinalysis?", "Proteins and Glucose", "Nitrites and Leukocytes", "Bilirubin", "RBCs", 2, "Nitrites and leukocytes in urine are markers of a UTI."));
bankBiochem3h03t2.push(new question("Which may be present in urine in people with diabetes?", "Proteins and Glucose", "Glucose and Ketones", "Nitrites and Leukocytes", "RBCs", 2, "Elevated glucose can indicate diabetes, and ketones in urine may indicate diabetic ketoacidosis."));
bankBiochem3h03t2.push(new question("What assesses potential liver disease in urinalysis?", "Proteins and Glucose", "Nitrites and Leukocytes", "Bilirubin", "Bacteria and Yeast", 3, "Bilirubin levels can assess potential liver disease in urinalysis."));
bankBiochem3h03t2.push(new question("What could indicate UTIs or contamination of a sample upon microscopic examination of urine?", "Proteins and Glucose", "Nitrites and Leukocytes", "Bilirubin", "Bacteria and Yeast", 4, "Bacteria and Yeast may be found during microscopic examination in urinalysis, and could indicate a UTI or contamination of the sample."));
bankBiochem3h03t2.push(new question("What is a 'cast' that you might find in urinalysis?", "Elevated levels of unwanted molecules", "Crystallized sediment", "Cylindrical impressions of nephrons", "Epithelial cells", 3, "Casts are cylindrical impressions of the nephrons, which may precipitate out of the solution."));
bankBiochem3h03t2.push(new question("What induces pre-renal acute kidney injury (AKI)?", "Significant decrease in GFR", "Intrinsic kidney damage", "Obstruction to urine flow", "Renal Tubular damage", 1, "A significant decrease in the GFR can induce pre-renal AKI."));
bankBiochem3h03t2.push(new question("What can pre-renal acute kidney injury (AKI) lead to if not treated immediately?", "Significant decrease in GFR", "Intrinsic kidney damage", "Obstruction to urine flow", "Renal Tubular damage", 2, "If not treated immediately, pre-renal AKI can lead to intrinsic AKI."));
bankBiochem3h03t2.push(new question("What is common in post-renal acute kidney injury (AKI)?", "Significant decrease in GFR", "Intrinsic kidney damage", "Obstruction to urine flow", "Renal Tubular damage", 3, "Obstruction to urine flow can cause post-renal AKI."));
bankBiochem3h03t2.push(new question("What can post-renal acute kidney injury (AKI) lead to if not treated immediately?", "Significant decrease in GFR", "Intrinsic kidney damage", "Obstruction to urine flow", "Renal Tubular damage", 4, "Prolonged post-renal AKI can lead to renal tubular damage if the obstruction is not removed immediately, as it increases hydrostatic pressure in the collecting ducts."));
bankBiochem3h03t2.push(new question("A patient has very high plasma urea, high plasma creatinine, low GFR, low urine sodium, and higher osmolality in urine than plasma. What is a likely explanation?", "Pre-renal AKI", "Intrinsic AKI", "Post-renal AKI", "No issue", 1, "Urea is more increaed than creatinine in the plasma, which indicates it may be pre- or post-renal AKI. In the urine, there is low sodium and higher osmolality than the plasma, which would be within range in post-renal AKI. Additionally, the GFR is low, which suggests pre-renal AKI."));
bankBiochem3h03t2.push(new question("A patient has high plasma urea and creatinine, low GFR, high urine sodium, and similar plasma and urine osmolalities. What is a likely explanation?", "Pre-renal AKI", "Intrinsic AKI", "Post-renal AKI", "No issue", 2, "A similar increase in plasma urea and creatinine, combined with high urine sodium and similar plasma and urine osmolalities, indicate intrinsic AKI."));
bankBiochem3h03t2.push(new question("What is a difference between acute kidney injury (AKI) and chronic kidney disease (CKD)?", "AKI is worse than CKD", "CKD acts faster than AKI", "AKI is reversible, CKD is not", "AKI can go untreated, CKD cannot", 3, "AKI acts fast, while CKD is slower, but CKD is not reversible, while AKI is."));
bankBiochem3h03t2.push(new question("What are biochemical markers of chronic kidney disease (CKD)?", "Increased urea, creatinine, H+", "Decreased HCO3-, Na+, GFR", "Steady urine osmolality", "All of the above", 4, "All of the above are markers of CKD."));
bankBiochem3h03t2.push(new question("How can you manage chronic kidney disease (CKD)?", "Strict control of sodium and fluid intake, as well as blood pressure and cardiovascular risk factors", "Manage anemia and endocrine disorders (diabetes)", "Renal replacement therapy (dialysis, kidney transplant)", "All of the above", 4, "All of the above can be used to manage CKD."));

//Lecture 5A Liver
bankBiochem3h03t2.push(new question("What is the functional unit of the liver?", "Hepatocyte", "Lobule", "Portal Triad", "Sinusoid", 2, "The lobule is the functional unit of the liver"));
bankBiochem3h03t2.push(new question("What do sinusoids do?", "Allow blood to flow into the liver", "Receive blood from the central vein to drain into the portal vein", "Mix oxygenated blood from the hepatic artery and nutrient-rich blood from the portal vein", "Fight bacteria in the liver", 3, "Sinusoids are where oxygenated blood mixes with nutrient-rich blood for substance exchange between the blood and liver cells."));
bankBiochem3h03t2.push(new question("What do Kupffer cells do?", "Allow blood to flow through the liver", "Fight bacteria", "Store nutrients", "Produce albumin", 2, "Kupffer cells are macrophages that fight bacteria in the liver, which may have been absorbed along with nutrients."));
bankBiochem3h03t2.push(new question("What do hepatocytes do?", "Store nutrients", "Detoxify", "Produce proteins", "All of the above", 4, "Hepatocytes receive fliud with oxygen and nutrients and store nutrients, detoxify, and produce proteins such as albumin. Excess waste and fat are carried away with bile."));
bankBiochem3h03t2.push(new question("What is the difference between unconjugated bilirubin and conjugated bilirubin?", "Unconjugated is water soluble, conjugated is not", "Unconjugated is excreted in the stool, conjugated is excreted in the urine", "Unconjugated needs to be transported in the blood by albumin, conjugated does not", "There is no difference", 3, "Unconjugated bilirubin is not water soluble and needs to be transported in the blood by albumin. Conjugated bilirubin is water soluble and does not need transporters."));
bankBiochem3h03t2.push(new question("An increase in what in the plasma can induce jaundice?", "Bilirubin", "Albumin", "Urine", "Urea", 1, "Hyperbilirubinemia can occur from an excess of either unconjugated or conjugated bilirubin, and can induce jaundice."));

//Lecture 5B Liver
bankBiochem3h03t2.push(new question("A patient has plasma AST 230 (8-33 IU/L), ALT 305 (10-50 IU/L), slightly elevated ALP and within range GGT, as well as elevated bilirubin. What is a likely explanation?", "Viral hepatitis", "Alcohol-induced hepatitis", "Toxic or ischemic hepatitis", "Chronic liver disease", 1, "An AST/ALT ratio <1 indicates viral hepatitis, along with a 5-50x increase in AST and ALT, mildly elevated ALP, and increased bilirubin."));
bankBiochem3h03t2.push(new question("A patient has plasma AST 197 (8-33 IU/L), ALT 95 (10-50 IU/L), elevated ALP and elevated GGT, as well as elevated bilirubin. What is a likely explanation?", "Viral hepatitis", "Alcohol-induced hepatitis", "Toxic or ischemic hepatitis", "Chronic liver disease", 2, "An AST/ALT ratio >2 indicates alcohol-induced hepatitis, along with a <10x increase in AST and ALT, elevated ALP and GGT, and increased bilirubin."));
bankBiochem3h03t2.push(new question("What does an AST/ALT ratio <1 indicate?", "Viral hepatitis", "Alcohol-induced hepatitis", "Toxic or ischemic hepatitis", "Chronic liver disease", 1, "An AST/ALT ratio <1 indicates viral hepatitis, along with a 5-50x increase in AST and ALT, mildly elevated ALP, and increased bilirubin."));
bankBiochem3h03t2.push(new question("What does an AST/ALT ratio >2 indicate?", "Viral hepatitis", "Alcohol-induced hepatitis", "Toxic or ischemic hepatitis", "Chronic liver disease", 2, "An AST/ALT ratio >2 indicates alcohol-induced hepatitis, along with a <10x increase in AST and ALT, elevated ALP and GGT, and increased bilirubin."));
bankBiochem3h03t2.push(new question("What does an AST and ALT reading 100x the URL indicate?", "Viral hepatitis", "Alcohol-induced hepatitis", "Toxic or ischemic hepatitis", "Chronic liver disease", 3, "An AST and ALT reading 100x the URL indicates toxic or ischemic heaptitis, typically 24-48 hours after the ingestion or ischemic event. Bilirubin levels in this case are minimal."));
bankBiochem3h03t2.push(new question("What does mildly elevated (~2x URL) AST and ALT for over 6 months indicate, and is it sufficient for diagnosis?", "Viral hepatitis, yes", "Alcohol-induced hepatitis, yes", "Toxic or ischemic hepatitis, no", "Chronic liver disease, no", 4, "A mildly elevated AST and ALT reading for over 6 months, along with within range ALP, GGT, and bilirubin levels, indicates chronic liver disease. However, the gold standard for diagnosis and evaluation of progression of this disease is a liver biopsy."));


//Lecture 6A Diabetes Mellitus
bankBiochem3h03t2.push(new question("What group of people is protected from Diabetes Mellitus (they cannot get it as easily)?", "Elderly men", "Premenopausal women", "Children under 5 years old", "Postmenopausal women", 2, "Premenopausal women are protected from DM, but it goes away after menopause and postmenopausal women experience DM at a rate similar to men."));
bankBiochem3h03t2.push(new question("What is Type 1 Diabetes Mellitus primarily caused by?", "Environmental Factors", "Autoimmune diseases", "Obesity", "Genetic Predisposition Alone", 2, "Type 1 DM is caused by autoimmune diseases."));
bankBiochem3h03t2.push(new question("What is Type 2 Diabetes Mellitus primarily caused by?", "Genetic Factors", "Metabolic Factors", "Environmental Factors", "All of the above", 4, "Type 2 DM is caused by a combination of genetic, metabolic, and environmental factors."));
bankBiochem3h03t2.push(new question("When does Gestational Diabetes Mellitus occur?", "Second or Third trimester of pregnancy", "First trimester of pregnancy", "After menopause", "Before conception", 1, "Gestational DM occurs in the second or third trimester of pregnancy, and typically resolves after birth but increases risk of Type 2 DM later in life."));
bankBiochem3h03t2.push(new question("What are symptoms of Diabetes Mellitus?", "Polyuria", "Hyperglycemia", "Fatigue", "All of the above", 4, "All of the options are symptoms of Diabetes Mellitus."));
bankBiochem3h03t2.push(new question("Why is thirst a symptom of Diabetes Mellitus?", "Increased insulin levels stimulate thirst centers", "Glucose directly triggers thirst centers", "Polyuria increases osmolality in the blood, activating thirst centres", "Low blood pressure causes thirst", 3, "Polyuria loses water in the blood, which increases osmolality. This triggers the release of ADH and activation of thirst centres."));
bankBiochem3h03t2.push(new question("What are symptoms of Diabetic Nephropathy (kidney damage)?", "Microalbuminuria", "Proteinuria when severe", "All of the above", "None of the above", 3, "Microalbuminuria is a symptom of Diabetic Nephropathy. Proteinuria is a symptom of severe Diabetic Nephropathy."));
bankBiochem3h03t2.push(new question("Which of the following is used to diagnose Diabetes Mellitus?", "Random blood glucose >7mM", "Polyuria + random blood glucose >11.1mM", "Fasting blood glucose >11.1mM", "Glycated HbA1C >7% (in adults, not if T1DM is suspected)", 2, "Diagnosis of DM requires one of the following: Symptoms (e.g. polyuria) + random blood glucose >11.1mM; Fasting (> or equal to 8 hours) glucose >7mM; Glycated Hb >6.5% in adults (not if T1DM is suspected)."));
bankBiochem3h03t2.push(new question("Which of the following is used to diagnose Diabetes Mellitus?", "Polyuria + fasting blood glucose >11.1mM", "Glycated HbA1C >6.5% (for T1DM only)", "Fasting blood glucose >7mM", "Random blood glucose >7mM", 3, "Diagnosis of DM requires one of the following: Symptoms (e.g. polyuria) + random blood glucose >11.1mM; Fasting (> or equal to 8 hours) glucose >7mM; Glycated Hb >6.5% in adults (not if T1DM is suspected)."));
bankBiochem3h03t2.push(new question("Which of the following is used to diagnose Diabetes Mellitus?", "Glycated HbA1C >6.5 (in adults, not if T1DM is suspected)", "Polyuria + random blood glucose >7mM", "Fasting blood glucose >11.1mM", "Random blood glucose >11.1mM", 1, "Diagnosis of DM requires one of the following: Symptoms (e.g. polyuria) + random blood glucose >11.1mM; Fasting (> or equal to 8 hours) glucose >7mM; Glycated Hb >6.5% in adults (not if T1DM is suspected)."));
bankBiochem3h03t2.push(new question("Which of the following is used to diagnose Diabetes Mellitus?", "Polyuria + random blood glucose >11.1mM", "Fasting blood glucose >7mM", "Glycated HbA1C >6.5 (in adults, not if T1DM is suspected)", "Any of the above", 4, "Diagnosis of DM requires one of the following: Symptoms (e.g. polyuria) + random blood glucose >11.1mM; Fasting (> or equal to 8 hours) glucose >7mM; Glycated Hb >6.5% in adults (not if T1DM is suspected)."));

bankBiochem3h03t2.push(new question("A 60 year old woman consults her family doctor because in the last month she has been feeling tired and has lost weight. She reports feeling very thirsty and that she needs to urinate more frequently than usual. She doesn’t feel pain or burning after urinating. What is a possible explanation, and is it sufficient for diagnosis?", "DM, yes", "DM, no", "UTI, yes", "UTI, no", 2, "Thirst and polyuria are common symptoms of DM. This is not sufficient for diagnosis, a follow-up random blood glucose measurement would confirm DM (>11.1mM)."));
bankBiochem3h03t2.push(new question("Routine blood work of a 52 year old man shows the following result: Fasting plasma glucose 6.1 mmol/L (2.8-5.6 mmol/L). What is the issue?", "T1DM", "T2DM", "Insulinoma", "No issue", 4, "Despite elevated plasma glucose, it is not sufficient for DM diagnosis, especially for a routine blood work."));

//Lecture 6B Diabetes Mellitus
bankBiochem3h03t2.push(new question("What is the glycated Hb test a good test for?", "T1DM", "T2DM", "All of the above", "None of the above", 2, "The glycated Hb test is good for chronic DM (T2DM) but not T1DM because hyperglycemia onsets too suddenly in T1DM."));
bankBiochem3h03t2.push(new question("Who is the Oral Glucose Tolerance Test usually performed for?", "Pregnant women (test for gestational DM)", "People with fasting glucose 6.1-6.9mM", "People with random glucose >11.1mM", "Options 1 and 2", 4, "The oral glucose tolerance test tests for glucose regulation capacity, and is tested on pregnant women for GDM and people with fasting glucose 6.1-6.9mM."));
bankBiochem3h03t2.push(new question("How many grams of glucose is taken for the Oral Glucose Tolerance Test?", "25g", "50g", "75g", "100g", 3, "For the OGTT, people first fast overnight, then fasting glucose is taken, then drink 75g glucose in 200-300mL water, then blood taken after 2 hours rest."));
bankBiochem3h03t2.push(new question("How much rest do people get between ingesting glucose and measuring glucose for the oral glucose tolerance test?", "30 minutes", "1 hour", "2 hours", "8 hours", 3, "For the OGTT, people first fast overnight, then fasting glucose is taken, then drink 75g glucose in 200-300mL water, then blood taken after 2 hours rest."));
bankBiochem3h03t2.push(new question("What glucose level indicates physiological conditions for the Oral Glucose Tolerance Test?", "<6.1mM", "6.1-7.8mM", "7.8-11.1mM", ">11.1mM", 1, "<6.1mM indicates physiological conditions for the OGTT."));
bankBiochem3h03t2.push(new question("What glucose level indicates impaired fasting glucose (IFG) for the Oral Glucose Tolerance Test?", "<6.1mM", "6.1-7.8mM", "7.8-11.1mM", ">11.1mM", 2, "6.1-7.8mM indicates IFG for the OGTT."));
bankBiochem3h03t2.push(new question("What glucose level indicates impaired glucose tolerance (IGT) for the Oral Glucose Tolerance Test?", "<6.1mM", "6.1-7.8mM", "7.8-11.1mM", ">11.1mM", 3, "7.8-11.1mM indicates IGT for the OGTT."));
bankBiochem3h03t2.push(new question("What glucose level indicates diabetes mellitus (DM) for the Oral Glucose Tolerance Test?", "<6.1mM", "6.1-7.8mM", "7.8-11.1mM", ">11.1mM", 4, ">11.1mM indicates DM for the OGTT."));
bankBiochem3h03t2.push(new question("What glucose level indicates prediabetes in pregnant women for the Oral Glucose Tolerance Test?", "<6.1mM", "6.1-9.9mM", ">=10.0mM", ">11.1mM", 2, "OGTT glucose 6.1-9.9mM indicates prediabetes in pregnent women."));
bankBiochem3h03t2.push(new question("What glucose level indicates diabetes in pregnant women for the Oral Glucose Tolerance Test?", "<6.1mM", "6.1-9.9mM", ">=10.0mM", ">11.1mM", 3, "OGTT glucose >=10.0mM indicates diabetes in pregnent women."));
bankBiochem3h03t2.push(new question("Which of the following does not count as prediabetes for the Oral Glucose Tolerance Test?", "Impaired fasting glucose", "Impaired glucose tolerance", "Diabetes mellitus", "All of the above are prediabetes", 3, "IFG and IGT are types of prediabetes."));
bankBiochem3h03t2.push(new question("How can C-peptides differentiate between T1DM and insulinoma?", "T1DM has low C-peptides due to insulin underproduction, insulinoma has high C-peptides due to insulin overproduction", "T1DM has low C-peptides due to autoimmune cells attacking them, insulinoma has high C-peptides due to healthy C-peptide production", "T1DM has high C-peptides due to insulin overproduction, insulinoma has low C-peptides due to C-peptide underproduction", "T1DM has high C-peptides due to immune cells secreting C-peptides, insulinoma has low C-peptides due to C-peptide comsumption", 1, "C-peptides are found in roughly equal amounts as insulin but do not affect glucose levels. T1DM has low C-peptides due to insulin underproduction, and insulinoma has high C-peptides due to insulin overproduction."));
bankBiochem3h03t2.push(new question("What does the GAD65 autoantibodies test for?", "T2DM, antibodies are synthesized in response to low insulin", "T1DM, antibodies can exist years before clinical onset", "Insulinoma, antibodies are synthesized in response to insulinoma", "Prediabetes, antibodies help prevention of diabetes", 2, "GAD65 autoantibodies can be tested for T1DM, and can be detected years before clinical onset."));
bankBiochem3h03t2.push(new question("What plasma glucose level is considered hypoglycemia?", "<2mM", "<2.8mM", "<7mM", "<11.1mM", 2, "Plasma glucose <2.8mM is considered hypoglycemia."));
bankBiochem3h03t2.push(new question("What are symptoms of hypoglycemia?", "Tiredness", "Confusion", "Weakness", "All of the above", 4, "Tiredness, confusion, sweating, palpitations, weakness, and blurred vision are symptoms of hypoglycemia."));
bankBiochem3h03t2.push(new question("What are possible causes of hypoglycemia?", "T1DM", "Insulinoma", "T2DM", "Options 1 and 2", 4, "T1DM and insulinoma can both cause hypoglycemia. Exogenous insulin for patients with T1DM can cause hypoglycemia, particularly after a missed meal. Insulinoma overproduces insulin, which overregulates glucose and can cause hypoglycemia."));

bankBiochem3h03t2.push(new question("A 42-year-old male presents to the clinic with polyuria, polydipsia, fatigue, and unintended weight loss over the past two months. He reports a family history of diabetes (his father diagnosed with Type 2 diabetes at age 50). Lab findings: Fasting Blood Glucose: 14.2 mmol/L (2.8-5.6 mmol/L), C-Peptide Level: 0.1 nmol/L (0.4–2.0 nmol/L), Insulin Level: Undetectable. What is a likely explanation?", "T1DM", "T2DM", "Insulinoma", "Hypoglycemia", 1, "Elevated fasting glucose >7mM (14.2mM in this case) indicates diabetes mellitus. Low C-peptides indicates T1DM."));
bankBiochem3h03t2.push(new question("32-year-old female presents to the ER with episodes of dizziness, confusion, sweating, and palpitations. She reports a few instances where she nearly fainted. Drinking juice or eating a carbohydrate-rich snack quickly relieves her symptoms. Lab results: Blood Glucose: 2.3 mmol/L (Normal: 2.8–5.6 mmol/L), C-Peptide Level: 2.5 nmol/L (Reference: 0.4–2.0 nmol/L), Insulin Level: 26 μU/mL (Reference: 2.6–24.9 μU/mL). What is a likely explanation?", "T1DM", "T2DM", "Insulinoma", "GDM", 3, "High insulin and C-peptide and low glucose indicates insulinoma. A next step would be a CT scan to locate the insulinoma and have it surgically removed."));

//Lecture 7 Cardiovascular Diseases
bankBiochem3h03t2.push(new question("How are free fatty acids transported in plasma?", "On their own", "With albumin", "With apoproteins", "None of the above", 2, "Free fatty acids are transported in plasma with albumin."));
bankBiochem3h03t2.push(new question("How are non-free fatty acid lipids transported in plasma?", "On their own", "With albumin", "With apoproteins", "None of the above", 3, "Other lipids (not free faatty acids) are transported in plasma with apoproteins to form lipoproteins."));
bankBiochem3h03t2.push(new question("What do chylomicrons mainly transport?", "Triglycerides", "Cholesterol", "Apoproteins", "Phospholipids", 1, "Chylomicrons are formed in enterocytes and are >90% triglycerides."));
bankBiochem3h03t2.push(new question("What do very-low density lipoproteins (VLDL) mainly transport?", "Triglycerides", "Cholesterol", "Apoproteins", "Phospholipids", 1, "VLDLs are formed in the liver and mainly transport endogenous triglycerides."));
bankBiochem3h03t2.push(new question("What do low density lipoproteins (LDL) mainly transport?", "Triglycerides", "Cholesterol", "Apoproteins", "Phospholipids", 2, "LDLs mainly transport cholesterol."));
bankBiochem3h03t2.push(new question("How do low density lipoproteins (LDL) release cholesterol?", "Binding LDL receptors on cells", "By secreting them with triglycerides", "By synthesizing cholesterol", "All of the above", 1, "LDLs bind LDL receptors on cells, and are internalized and degraded, releasing cholesterol."));
bankBiochem3h03t2.push(new question("What is the rate-limiting enzyme for cholesterol synthesis in the liver?", "HMG-CoA hydrogenase", "Acetyl-CoA reductase", "HMG-CoA reductase", "Acetyl-CoA hydrogenase", 3, "HMG-CoA reductase is the rate-limiting enzyme for cholesterol synthesis in the liver."));
bankBiochem3h03t2.push(new question("What do high density lipoproteins (HDL) mostly made of?", "Triglycerides", "Apoproteins", "Phospholipids", "Options 2 and 3", 4, "HDLs are mostly made of apoproteins and phospholipids."));
bankBiochem3h03t2.push(new question("What do high density lipoproteins (HDL) transport?", "Forward transport of triglycerides", "Reverse transport of triglycerides", "Forward transport of cholesterol", "Reverse transport of cholesterol", 4, "HDLs mediate reverse cholesterol transport to remove cholesterol."));
bankBiochem3h03t2.push(new question("What is atherosclerosis?", "Heart attack", "High triglycerides", "Plaque buildup", "Cardiac troponin buildup", 3, "Atherosclerosis is plaque buildup in the arteries."));
bankBiochem3h03t2.push(new question("What does not increase CVD risk?", "Hypertriglyceridemia", "High LDL", "High HDL", "All of the above increase CVD risk", 3, "High HDL does not increase CVD risk as it mediates cholesterol removal. Low HDL is associated with CVD risk."));
bankBiochem3h03t2.push(new question("What can cardiac troponin (cTn) levels tell us about myocardial infarctions?", "Levels above URL indicate MI", "2x increase within 3 hours of baseline could indicate MI", "Levels below LRL indicate MI", "Cardiac troponin is unrelated to MI", 2, "A significant increase cTn levels (e.g. double within 3 hours of baseline measurement) indicates MI."));
bankBiochem3h03t2.push(new question("What is an optimal LDL level for someone with a heart disease / heart attack history?", "<1.8mM", "<2.6mM", "<3.3mM", "<7mM", 1, "LDL <1.8mM is good for someone with a heart disease / heart attack history."));
bankBiochem3h03t2.push(new question("What is an optimal LDL level for someone with CVD risk + DM history?", "<1.8mM", "<2.6mM", "<3.3mM", "<7mM", 2, "LDL <2.6mM is good for someone with CVD risk + DM history."));
bankBiochem3h03t2.push(new question("What is an optimal LDL level for someone with no known CVD risk?", "<1.8mM", "<2.6mM", "<3.3mM", "<7mM", 3, "LDL <3.3mM is good for someone with no known CVD risk."));

bankBiochem3h03t2.push(new question("If a patient has LDL 3.5 mmol/L (from routine blood work), is the patient likely healthy?", "Yes", "No", "-", "-", 2, "3.5mM > the recommended <3.3mM for healthy individuals."));
bankBiochem3h03t2.push(new question("If a patient has LDL 2.4 mmol/L and has had a heart attack two years ago, is the patient likely healthy?", "Yes", "No", "-", "-", 2, "2.4mM > the recommended <1.8mM for individuals with a heart disease / heart attack history."));
bankBiochem3h03t2.push(new question("If a patient has LDL 2.0 mmol/L and has diabetes, is the patient likely healthy?", "Yes", "No", "-", "-", 1, "2.0mM < the recommended <2.6mM for individuals with CVD risk + DM history, patient is likely healthy."));
bankBiochem3h03t2.push(new question("If a patient has LDL 4 mmol/L and has already tried lifestyle modifications, what could be a next step?", "Pharmacologic therapy", "Nothing", "Strict diet", "Test for diabetes", 1, "Pharmacologic therapy can be done to reduce LDL concentration."));
bankBiochem3h03t2.push(new question("A patient has yellow masses around the eye and a nodule attached to the tendon of the hand. In the medical history, the patient's grandfather suddenly passed in his 50s. Lipid profile: Total cholesterol 13.2 mmol/L (3.5-5.2 mmol/L), HDL cholesterol 1.3 mmol/L (>1.3 mmol/L females; >1.0 mmol/L males), LDL cholesterol 11.4 mmol/L (2.6-3.3 mmol/L people w/o CHD), Triglyceride 1.3 mmol/L (<1.7 mmol/L). What is a likely explanation and what should be tested to confirm?", "Familial hypertriglyceridemia, test first degree relatives", "Environmental hypertriglyceridemia, test blood glucose", "Familial hypercholesterolemia, test first degree relatives", "Environmental hypercholesterolemia, test blood glucose", 3, "High cholesterol + LDL, and a potential family history of hypercholesterolemia, indicates it could be familial hypercholesterolemia. Next steps would be to confirm by testing first degree relatives."));
bankBiochem3h03t2.push(new question("A 53 year old male developed severe abdominal pain in the last hour and a half. The patient has difficulty describing the characteristics of the pain. It seems it is irradiating to the back as the patient keeps pointing at it. Plasma values: Total cholesterol 4.7 mmol/L (3.5-5.2 mmol/L), HDL cholesterol 1.3 mmol/L (>1.3 mmol/L females; >1.0 mmol/L males), LDL cholesterol 3 mmol/L (2.6-3.3 mmol/L people w/o CHD), Triglyceride 7 mmol/L (<1.7 mmol/L). What is a likely explanation and what are next steps?", "Hypertriglyceridemia, CT scan to exclude other causes then assess plasma amylase (>10x) and lipase (>3x) for pancreatitis", "Hypotriglyceridemia, CT scan to exclude other causes then assess plasma amylase (>10x) and lipase (>3x) for pancreatitis", "Hypertriglyceridemia, try pharmacologic therapies", "Hypotriglyceridemia, try pharmacologic therapies", 1, "High trigylcerides indicates hypertriglyceridemia, next steps are a CT scan to rule out other causes then a test of plasma amylase and lipase to test for pancreatitis, since it is associated with high triglycerides."));
bankBiochem3h03t2.push(new question("50 year old man arrives at the ER in the past 30 minutes for acute chest pain. The pain was central, radiated to the left arm and jaw, and crushing in nature. The patient is a heavy smoker. What is a likely explanation?", "CHD due to smoking", "DM due to smoking", "CHD due to genetics", "DM due to genetics", 1, "The patient likely has CHD, based on chest pain, and smoking likely had an influence on the CHD."));
bankBiochem3h03t2.push(new question("72 year old woman goes to the family doctor because in the past few days she has been feeling unusually tired. She also has nausea and reports “difficulty digesting” as if she felt an uncomfortable pressure right below her chest which comes and goes. She also experiences shortness of breath. The family doctor sends her straight to the ER. Why?", "Acute myocardial infarction", "Chronic CVD", "T1DM", "T2DM", 1, "Chest pain, nausea, and tiredness indicate AMI. An electrocardiogram (ECG) and cardiac troponin (cTn) levels could be taken to confirm."));

//Lecture 8A Complete Blood Count
bankBiochem3h03t2.push(new question("What is considered an abnormal result in complete blood count?", "Results outisde reference range", "Immature RBCs, WBCs", "Other abnormal cells", "All of the above", 4, "All of the above are abnormal and would be flagged for a blood smear."));
bankBiochem3h03t2.push(new question("What Hb level is considered anemia in non-pregnant women?", "<11g/dL", "<12g/dL", "<13g/dL", "<14g/dL", 2, "Hb <12g/dL is anemia in non-pregnant women."));
bankBiochem3h03t2.push(new question("What Hb level is considered anemia in pregnant women?", "<11g/dL", "<12g/dL", "<13g/dL", "<14g/dL", 1, "Hb <11g/dL is anemia in pregnant women."));
bankBiochem3h03t2.push(new question("What Hb level is considered anemia in men?", "<11g/dL", "<12g/dL", "<13g/dL", "<14g/dL", 3, "Hb <13g/dL is anemia in men."));
bankBiochem3h03t2.push(new question("What is considered microcytic anemia?", "Anemia + MCV < LRL", "Anemia + MCV within range", "Anemia + MCV > URL", "Anemia + MCV out of range in either direction", 1, "Microcytic anemia occurs when anemia is joint by a mean corpuscular volume (MCV, measures RBC size) below the LRL."));
bankBiochem3h03t2.push(new question("What is a cause of microcytic anemia?", "RBC structural issues", "Blood loss", "Vitamin B12 / folate malabsorption", "All of the above", 1, "RBC structural issues can cause anemia as well as decrease mean corpuscular volume (MCV)."));
bankBiochem3h03t2.push(new question("What is considered normocytic anemia?", "Anemia + MCV < LRL", "Anemia + MCV within range", "Anemia + MCV > URL", "Anemia + MCV out of range in either direction", 2, "Normocytic anemia occurs when anemia is joint by a mean corpuscular volume (MCV, measures RBC size) within range."));
bankBiochem3h03t2.push(new question("What is a cause of normocytic anemia?", "RBC structural issues", "Blood loss", "Vitamin B12 / folate malabsorption", "All of the above", 2, "Blood loss can cause anemia without disrupting mean corpuscular volume (MCV)."));
bankBiochem3h03t2.push(new question("What is considered macrocytic anemia?", "Anemia + MCV < LRL", "Anemia + MCV within range", "Anemia + MCV > URL", "Anemia + MCV out of range in either direction", 3, "Macrocytic anemia occurs when anemia is joint by a mean corpuscular volume (MCV, measures RBC size) above the URL."));
bankBiochem3h03t2.push(new question("What is a cause of macrocytic anemia?", "RBC structural issues", "Blood loss", "Vitamin B12 / folate malabsorption", "All of the above", 3, "Vitamin B12 / folate malabsorption can cause anemia as well as increase mean corpuscular volume (MCV)."));
bankBiochem3h03t2.push(new question("What is the point of a blood smear?", "To confirm or exclude results", "To detect issues", "To test blood type", "An alternate blood test for pregnant women", 1, "A blood smear is done after the complete blood count flags a sample to confirm or exclude results."));

bankBiochem3h03t2.push(new question("39 year old female has been feeling unusually tired in the past two weeks. The doctor notices the patient looks very pale. CBC shows: RBC: 3.0 (Females, adult, nonpregnant: 4.0-5.0 x10^12/ L), Hb: 10 (11.5-15.5 g/dL), MCV: 68.5 (77-95 fL). What is a likely explanation?", "Microcytic anemia", "Normocytic anemia", "Macrocytic anemia", "No issue", 1, "Anemia (Hb <12g/dL + RBC < LRL) + low MCV indicates microcytic anemia."));
bankBiochem3h03t2.push(new question("73 year old patient with known CKD has been feeling very tired in the past 3 weeks with difficulty going up a flight of stairs. CBC: RBC: 4.0 (males: 4.5-6.0 x10^12/ L ), Hb: 12.7 (males: 14-17.5 g/dL), MCV: 85 (77-95 fL). What is a likely explanation?", "Microcytic anemia", "Normocytic anemia", "Macrocytic anemia", "No issue", 2, "Anemia (Hb <13g/dL + RBC < LRL) + MCV within range indicates normocytic anemia."));
bankBiochem3h03t2.push(new question("69 year old female patient with advanced chronic hepatitis has been experiencing unusual fatigue in the last 10 days. CBC: RBC: 3.5 (Females, adult, nonpregnant: 4.0-5.0 x10^12/ L), Hb: 9.7 (11.5-15.5 g/dL), MCV: 100 (77-95 fL). What is a likely explanation?", "Microcytic anemia", "Normocytic anemia", "Macrocytic anemia", "No issue", 3, "Anemia (Hb <12g/dL + RBC < LRL) + high MCV indicates macrocytic anemia. Hepatitis indicates malabsorption as a possible cause."));

//Lecture 8B Complete Blood Count
bankBiochem3h03t2.push(new question("", "___", "___", "___", "___", 1, "e"));

//Lecture 9 Thyroid
bankBiochem3h03t2.push(new question("", "___", "___", "___", "___", 1, "e"));
