//Bank questions here
//bank3h03.push(new question("", "", "", "", "", 1, ""));

//Lecture 1
bank3h03.push(new question("What is the difference between serum and plasma?", "Serum lacks clotting factors that plasma has", "Serum is the aqueous phase of blood, while plasma is coagulated blood", "Serum has white blood cells and platelets which can provide more information about the blood", "There is no difference between serum and plasma", 1, "Serum and plasma are both from the aqueous phase of blood, but unlike serum, plasma still has coagulation factors despite not clotting. Plasma is preserved by anticoagulants."));
bank3h03.push(new question("What is the difference between the Reference Interval (RI) and the Clinical Decision Limit (CDL)?", "The RI is arbitrary while the CDL is based on population statistics", "The RI is used for clinical decision making while the CDL is used for identifying deviations from the average in the general population", "The RI is based on the general population and the CDL is based on the clinical population", "The RI is based on clinical studies and guidelines while the CDL is the 95% central interval of the reference distribution", 3, "The RI is based on the general population, and is based on the 95% central interval of the reference distribution. The CDL is based on studies and guidelines for the clinical population and is used for clinical decision making. The CDL can change because of how they are based."));
bank3h03.push(new question("What is the difference between sensitivity in tests and specificity?", "Sensitivity is the ability to identify patients without the disease and specificity is the ability to identify patients with the disease", "High sensitivity is good for identifying a diagnosis, while high specificity is good for ruling out a diagnosis", "Sensitivity is the percentage of unaffected individuals who have a negative test result, specificity is the percentage of affected individuals who have a positive test result", "Sensitivity is measured by how often a positive test picks up a disease, while specificity is measured by how good a test is at isolating a disease", 4, "Sensitivity is calculated based on how well a test picks up a disease, and specificity is calculated based on how specific it is only to individuals who are truly affected."));
bank3h03.push(new question("In a population that is given a test for disease, 6 return a true negative, 1 returns a false negative, 1 returns a true positive, and 2 return a false positive. What is the sensitivity and specificity of the test?", "Sensitivity: 0.5, Specificity: 0.75", "Sensitivity: 50, Specificity: 75", "Sensitivity: 33.3, Specificity: 85.7", "Sensitivity: 0.333, Specificity: 0.857", 2, "Sensitivity is calculated by the amount of individuals with a true positive divided by the amount of affected individuals, times 100 (TP/(TP+FN) * 100), and specificity is calculated by the amount of individuals with a true negative divided by the amount of unaffected individuals, times 100 (TN/(TN+FP) * 100)."));

//Lecture 2A
bank3h03.push(new question("", "", "", "", "", 1, ""));
bank3h03.push(new question("", "", "", "", "", 1, ""));
bank3h03.push(new question("", "", "", "", "", 1, ""));
