//Bank questions here
//bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));

//Lecture 5
bankBiochem3d03t2.push(new question("How are enzymes regulated?", "Gene expression", "Allosteric regulation", "Feedback loops", "All of the above", 4, "Enzymes are regulated through gene expression, allosteric reguation, and feedback inhibition."));
bankBiochem3d03t2.push(new question("How does calcium link muscle contraction to ATP production?", "___", "By initiating muscle contraction as well as stimulating glycolysis, PDH, and some TCA enzymes", "___", "___", 2, "Calcium is responsible for initiating muscle contraction as well as stimulating many enzymes linked to ATP production."));
bankBiochem3d03t2.push(new question("Is glycogen phosphorylase phosphorylated when active?", "Yes", "No", "-", "-", 1, "Glycogen phosphorylase, responsible for glycogenolysis, is phosphorylated when active."));
bankBiochem3d03t2.push(new question("What are allosteric activators and inhibitors of glycogen phosphorylase?", "Activators: AMP; Inhibitors: ATP, G6P", "___", "___", "___", 1, "Activators include AMP, inhibitors include ATP and G6P."));
bankBiochem3d03t2.push(new question("What are covalent / hormonal activators and inactivators of glycogen phosphorylase?", "___", "___", "Activators: epinephrine, glucagon; Inactivators: insulin", "___", 3, "Activators include epinephrine and glucagon, inactivators include insulin."));
bankBiochem3d03t2.push(new question("What are allosteric activators and inhibitors of glycogen synthase?", "___", "___", "___", "Activators: ATP, G6P; Inhibitors: none", 4, "Activators include ATP and G6P."));
bankBiochem3d03t2.push(new question("What are covalent / hormonal activators and inactivators of glycogen synthase?", "___", "Activators: insulin; Inactivators: epinephrine, glucagon", "___", "___", 2, "Activators include insulin, inactivators include epinephrine and glucagon."));
bankBiochem3d03t2.push(new question("Which is not a correct part of the epinephrine signaling pathway?", "Epinephrine binds β-andrenergic receptor", "β-andrenergic receptor interacts with G-protein", "G-protein activates adenylate cyclase", "Adenylate cyclase: cAMP → ATP", 4, "Adenylate cyclase catalyzes the reaction from ATP to cAMP, not cAMP to ATP."));
bankBiochem3d03t2.push(new question("Which is not a correct part of the epinephrine signaling pathway?", "cAMP activates cAMP-dependent protein kinase", "cAMP-dependent kinase phosphorylates phosphorylase kinase", "Phosphorylase kinase inactivates glycogen phosphorylase", "Phosphorylase kinase inactivates glycogen synthase", 3, "Phosphorylase kinase activates glycogen phosphorylase and inactivates glycogen synthase."));
bankBiochem3d03t2.push(new question("What is true about glucagon and insulin?", "ɑ-cells produce insulin, β-cells produce glucagon", "ɑ-cells produce glucagon, β-cells produce insulin", "Both ɑ-cells and β-cells produce insulin and glucagon", "Both ɑ-cells and β-cells inhibit insulin and glucagon production", 2, "ɑ-cells produce glucagon during postprandial condition and β-cells produce insulin during fasting condition."));
bankBiochem3d03t2.push(new question("What are allosteric activators and inhibitors of hexokinase?", "___", "___", "___", "Activators: G6P; Inhibitors: none", 4, "Activators include G6P."));
bankBiochem3d03t2.push(new question("What are allosteric activators and inhibitors of PFK?", "Activators: ADP, AMP, F6P; Inhibitors: ATP, PEP, citrate", "___", "___", "___", 1, "Activators include ADP, AMP, and F6P, inhibitors include ATP, PEP, and citrate."));
bankBiochem3d03t2.push(new question("What cofactors are required for the PDH complex?", "NAD+", "CoA", "FAD", "All of the above", 4, "NAD+, thiamine pyrophosphate, lipoic acid, CoA, and FAD are required for the PDH complex."));
bankBiochem3d03t2.push(new question("Which is false about the PDH complex?", "It is active when phosphorylated", "It is activated by PDH phosphatase, and inactivated by PDH kinase", "It is made up of 3 enzymes", "NADH and acetyl-CoA are end-product inhibitors", 1, "PDH is active when dephosphorylated."));
bankBiochem3d03t2.push(new question("What are allosteric activators and inhibitors of PDH phosphatase?", "___", "___", "Activators: Ca, Mg; Inhibitors: none", "___", 3, "Activators include calcium and magnesium."));
bankBiochem3d03t2.push(new question("What are allosteric activators and inhibitors of PDH kinase?", "___", "Activators: NADH, acetyl-CoA, ATP; Inhibitors: ADP, pyruvate, Ca, Mg", "___", "___", 2, "Activators include NADH, acetyl-CoA, and ATP, inhibitors include ADP, pyruvate, calcium, and magnesium."));
bankBiochem3d03t2.push(new question("TCA cycle start---------------------", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
bankBiochem3d03t2.push(new question("", "", "", "", "", 1, ""));
